services:
  wiremock:
    image: wiremock/wiremock:3.10.0
    container_name: wiremock
    ports:
      - "9999:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files